namespace Depi_Session09
{
    class Program
    {
        static void Main(string[] args)
        {
            Part1_PrimaryConstructorAndRecords();
            Part2_Singleton();
            Part3_VarAndDynamic();
            Part4_AnonymousTypes();
            Part5_ExtensionMethods();
        }

        // =====================================================================
        // Part 1 - Primary Constructor & Records
        // =====================================================================
        static void Part1_PrimaryConstructorAndRecords()
        {
            Console.WriteLine("===== Part 1: Primary Constructor & Records =====");

            // ---------- Q2 (class) ----------
            Patient patient01 = new(1, "Ahmed Ali", "01012345678", "Asthma");
            Patient patient02 = new(1, "Ahmed Ali", "01012345678", "Asthma");

            Console.WriteLine(patient01);

            // 1) GetHashCode of both
            Console.WriteLine($"patient01 hash: {patient01.GetHashCode()}");
            Console.WriteLine($"patient02 hash: {patient02.GetHashCode()}");
            // Are they equal?  NO.
            // Why? Patient is a CLASS (reference type). The default GetHashCode() is based on the
            // object's identity (its reference in memory), not on its values.
            // Two different objects => two different references => different hash codes.

            // 2) Equals
            Console.WriteLine($"patient01.Equals(patient02): {patient01.Equals(patient02)}");   // False
            // Why? The default Object.Equals compares REFERENCES, not values.
            // Same values but they are two different objects in memory => false.

            // 3) Assign then check again
            patient01 = patient02;
            Console.WriteLine($"After assignment -> Equals: {patient01.Equals(patient02)}");   // True
            Console.WriteLine($"After assignment -> hashes: {patient01.GetHashCode()} / {patient02.GetHashCode()}");
            // What changed? Now both variables point to the SAME object in memory,
            // so the references are the same => Equals is true and the hash codes are the same.

            // ---------- Q3 (record) ----------
            Console.WriteLine();
            PatientDto dto01 = new PatientDto(1, "Ahmed Ali", "01012345678");
            PatientDto dto02 = new PatientDto(1, "Ahmed Ali", "01012345678");

            Console.WriteLine($"dto01 hash: {dto01.GetHashCode()}");
            Console.WriteLine($"dto02 hash: {dto02.GetHashCode()}");
            Console.WriteLine($"dto01.Equals(dto02): {dto01.Equals(dto02)}");   // True
            Console.WriteLine($"dto01 == dto02: {dto01 == dto02}");             // True

            dto01 = dto02;
            Console.WriteLine($"After assignment -> Equals: {dto01.Equals(dto02)}");   // True

            // Difference between class and record:
            // - Class: equality and GetHashCode are REFERENCE-based by default. Two objects with the
            //   same values are NOT equal (until we assign one to the other so they share a reference).
            // - Record: equality and GetHashCode are VALUE-based (generated by the compiler).
            //   Two records with the same values are equal with identical hash codes, before and after assignment.
            //   Also records give us a nice ToString, == and != for free.

            // ---------- Q4 (mapper) ----------
            Console.WriteLine();
            Patient patient03 = new(2, "Mona Samir", "01234567890", "Allergy");
            PatientDto mapped = PatientMapper.MapFromModelToDto(patient03);
            Console.WriteLine(mapped);   // PatientDto { Id = 2, FullName = Mona Samir, PhoneNumber = 01234567890 }
            Console.WriteLine();
        }

        // =====================================================================
        // Part 2 - Singleton
        // =====================================================================
        static void Part2_Singleton()
        {
            Console.WriteLine("===== Part 2: Singleton =====");

            // Q6) call GetLogger() four times
            AppLogger logger01 = AppLogger.GetLogger();
            AppLogger logger02 = AppLogger.GetLogger();
            AppLogger logger03 = AppLogger.GetLogger();
            AppLogger logger04 = AppLogger.GetLogger();

            Console.WriteLine(logger01.GetHashCode());
            Console.WriteLine(logger02.GetHashCode());
            Console.WriteLine(logger03.GetHashCode());
            Console.WriteLine(logger04.GetHashCode());

            // Observation: all four hash codes are IDENTICAL.
            // Why? The constructor is private so we can't use "new" outside the class.
            // GetLogger() creates the object only on the first call (when _instance is null)
            // and afterwards returns the same stored instance.
            // So all four variables point to ONE object (same reference => same hash code).

            logger01.Log("Application started");
            Console.WriteLine();
        }

        // =====================================================================
        // Part 3 - var & dynamic
        // =====================================================================
        static void Part3_VarAndDynamic()
        {
            Console.WriteLine("===== Part 3: var & dynamic =====");

            // Q7-1) target-typed new: the type is written on the left, "new(...)" infers it
            Patient p1 = new(10, "Khaled Hassan", "01111111111", "None");

            // Q7-2) var: the compiler infers the type from the right side
            var p2 = new Patient(11, "Sara Mahmoud", "01222222222", "Hypertension");

            // Q7-3) dynamic
            dynamic p3 = new Patient(12, "Omar Youssef", "01555555555", "None");
            Console.WriteLine(p3);   // ToString is resolved at run time

            Console.WriteLine(p1);
            Console.WriteLine(p2);

            // Q7-4) Difference between var and dynamic:
            // - var  : type is resolved at COMPILE TIME (the compiler infers it and it never changes).
            //          You get IntelliSense and compile-time errors, e.g. p2.NotExist -> compile error.
            // - dynamic : type is resolved at RUN TIME. The compiler skips type checking,
            //          so p3.NotExist compiles fine but throws RuntimeBinderException when it runs.
            Console.WriteLine();
        }

        // =====================================================================
        // Part 4 - Anonymous Types
        // =====================================================================
        static void Part4_AnonymousTypes()
        {
            Console.WriteLine("===== Part 4: Anonymous Types =====");

            var doctor01 = new { Name = "Sara", Specialty = "Cardiology", ExperienceYears = 8, Salary = 25_000 };
            var doctor02 = new { Name = "Sara", Specialty = "Cardiology", ExperienceYears = 8, Salary = 25_000 };

            // 1) properties
            Console.WriteLine($"{doctor01.Name} - {doctor01.Specialty}");

            // 2) hash codes -> equal
            Console.WriteLine($"doctor01 hash: {doctor01.GetHashCode()}");
            Console.WriteLine($"doctor02 hash: {doctor02.GetHashCode()}");

            // 3) type -> compiler-generated type, something like <>f__AnonymousType0`4[String,String,Int32,Int32]
            Console.WriteLine(doctor01.GetType());

            // 4) Equals -> True
            Console.WriteLine($"doctor01.Equals(doctor02): {doctor01.Equals(doctor02)}");

            // 5) ToString -> { Name = Sara, Specialty = Cardiology, ExperienceYears = 8, Salary = 25000 }
            Console.WriteLine(doctor01.ToString());

            // Comparison:
            // - Anonymous type: the compiler generates Equals/GetHashCode/ToString, and equality is VALUE-based
            //   (same property names, types, order and values => equal). Same as a record in behavior.
            //   Properties are read-only, and it can only be used locally (with var).
            // - Class: equality is REFERENCE-based by default (unless we override Equals/GetHashCode ourselves).
            // - Record: equality is VALUE-based, and unlike anonymous types it has a real name
            //   so it can be used as a return type / parameter and across the whole project.
            Console.WriteLine();
        }

        // =====================================================================
        // Part 5 - Extension Methods
        // =====================================================================
        static void Part5_ExtensionMethods()
        {
            Console.WriteLine("===== Part 5: Extension Methods =====");

            // Q10
            Console.WriteLine("Stethoscope".IsShorterThan(5));   // False (length is 11)
            Console.WriteLine("Ab".Repeat(4));                   // AbAbAbAb
        }
    }
}
